### ISSUE TITLE
[Umbrella Ticket] Rate Limiting - Capacity & Throughput Rate Limiting

### ISSUE THREAD

**Issue by Olshansk** [buildwithgrove/path#10]
## Objective

Implement Rate Limiting MVP.

## Origin Document

The entire portal stripe + rate limiter migration found (in part) [in this notion doc](https://www.notion.so/buildwithgrove/Portal-Updates-for-Pricing-Cutover-4c3e7d29c7bd48e1baf5c5642fcd9182?pvs=4).

## Goals

- Achieve parity with rate limiting in `portal`
- Set Grove up for migration (in the future) from `portal-middleware` to `path`
- Prepare for a future ticket related to stripe billing

## Deliverables

1. Mini docs for rate limiting (to be turned into docusaurus documentation)
	- [ ] 1-2 pager on capacity rate limiting
	- [ ] 1-2 pager on throughput rate limiting
2. Implement rate limiting
	- [ ] Implement Capacity Rate Limiting
	- [ ] Implement Throughput Rate Limiting
3. Make the following **configurable** (env or yaml) after which the user is throttled
    - [ ] Capacity rate limiting in TPS / Month
    - [ ] Throughput rate limiting in TPS / second
4. Implement with a "global" rate limiting in mind, but integrate with #11 shortly after

## Non-goals / Non-deliverables

- Implement billing and/or stripe integration

## Sanity Check

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---
**Creator**: @Olshansk 
**Co-Owners**: @commoddity

**Comment by fredteumer** [comment]
One thought for consideration: Right now rate limiting and throughput limiting are applied at the `Plan` level and not the `User` level. Just want to check that assumption as we prepare for migration.

**Comment by commoddity** [comment]
> One thought for consideration: Right now rate limiting and throughput limiting are applied at the `Plan` level and not the `User` level. Just want to check that assumption as we prepare for migration.

This is a good callout. While keeping the assumption that limits are set at the plan level, the actual blocking of requests should still happens at the `UserApp` (CKA `Portal App` in the middleware) level IMO.

**Comment by Olshansk** [comment]
@fredteumer Also note that we have introduced new terminology::

- `Capacity limiting` in TPS / Month
- `Throughput limiting` in TPS / second

Rate limiting is a more general purpose term that captures both.

**Comment by commoddity** [comment]
Draft PR for implementing Envoy Rate Limiter Proposal here:
https://github.com/buildwithgrove/path/pull/29
