### ISSUE TITLE
[Umbrella Ticket] PATH Embedded QoS

### ISSUE THREAD

**Issue by adshmh** [buildwithgrove/path#19]
## Objective

Build the foundation for Quality of Service on JSONRPC, EVM, and RESTful services.

## Origin Document

- Filter out potentially invalid requests before they get sent to service endpoints.
- Validate responses received from service endpoints to minimize the number of invalid responses that reach end users.
- Help filter out available endpoints that do not comply with the spec of the target service, to reduce the need for retries on service requests, leading to improved quality of service for the user.

## Goals

- Clearly invalid requests should be blocked before reaching service endpoints, e.g. a JSONRPC request with no method.
- Clearly responses should be blocked before reaching the user, e.g. a non-JSONRPC response to a JSONRPC service request.

## Deliverables
- [ ] JSONRPC basic validation of requests and responses
- [ ] EVM basic validation (e.g. valid method name), on both requests and responses
- [ ] RESTful services basic validation against a TBD spec, e.g. openAPI.

## Non-goals / Non-deliverables

- Guaranteeing the validity of a request before sending it out to a service endpoint, e.g. processing a `eth_sendTransaction` to ensure the sender has enough balance.

- Guaranteeing the validity of a response before returning it to the user, e.g. verifying the actual contents of a block received in response to an `eth_blockNumber` request.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: [@adshmh ]
**Co-Owners**: [@Olshansk ]
